#!/bin/sh
#
# Copyright (C) 2011-2012 OpenWrt.org
#

[ -e /etc/config/ubootenv ] && exit 0

touch /etc/config/ubootenv

. /lib/uboot-envtools.sh
. /lib/functions.sh

board=$(board_name)

ubootenv_add_ubi_default() {
	. /lib/upgrade/nand.sh
	local envubi=$(nand_find_ubi ubi)
	local envdev=/dev/$(nand_find_volume $envubi ubootenv)
	local envdev2=/dev/$(nand_find_volume $envubi ubootenv2)
	ubootenv_add_uci_config "$envdev" "0x0" "0x1f000" "0x1f000" "1"
	ubootenv_add_uci_config "$envdev2" "0x0" "0x1f000" "0x1f000" "1"
}

case "$board" in
glinet,gl-mt6000 |\
jdcloud,re-cp-03)
	env_dev=$(find_mmc_part "u-boot-env")
	[ -n "$env_dev" ] && ubootenv_add_uci_config "$env_dev" "0" "0x80000"
	;;
*360,t7* |\
livinet,zr-3020*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x20000" "0x20000" "1"
	;;
h3c,nx30pro |\
*clt,r30b1* |\
ruijie,rg-x60-pro* )
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x80000" "0x20000" "4"
	;;
*imou,lc-hx3001*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x80000" "0x80000" "1"
	;;
xiaomi,mi-router-ax3000t* |\
xiaomi,mi-router-wr30u* |\
xiaomi,redmi-router-ax6000*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x10000" "0x20000" "1"
	;;
nradio,wt9103 |\
*konka,komi-a31*)
	ubootenv_add_uci_config "/dev/mtd2" "0x0" "0x20000" "0x80000" "1"
	;;
cmcc,rax3000m |\
asus* )
	ubootenv_add_uci_config "/dev/mtd0" "0x100000" "0x20000" "0x20000"
	;;
esac

config_load ubootenv
config_foreach ubootenv_add_app_config ubootenv

exit 0
